### ISSUE TITLE
Is not attempting to automatically free the underlaying buffer intentional?

### ISSUE THREAD

**Issue by glampert** [ocornut/str#2]
The title pretty much say it. Since `Str` doesn't have a user defined destructor, if the buffer was heap allocated it won't be automatically freed. Is this the intended behavior? I didn't find any comments on that regard stating that `clear()` should be called manually to ensure cleanup, so I'm just looking for clarification on the intent.

Thanks.

**Comment by ocornut** [comment]
No you are right, it is an overlook (and gives you an indication of how much I have actually used this class so far!). Will fix.
