### ISSUE TITLE
Str32 type collision on Mac (MacTypes.h)

### ISSUE THREAD

**Issue by jlaumon** [ocornut/str#6]
Hey,

There's a also `typedef char Str32[33]` in [MacTypes.h](https://opensource.apple.com/source/CarbonHeaders/CarbonHeaders-18.1/MacTypes.h), and this header is included in a lot of places on mac (inside opengl headers among other things). 

No #idefs or anything to prevent MacTypes.h from declaring it (as far as I can tell), so adding a namespace to Str or renaming it is the only solution I see.

I don't have good suggestion for namespaces or renaming 🤔 (unless if you want to start an Omar branding? `Oc`, `Omar`, `Om`? Or `Im` ?). Maybe renaming StrXX to Str_XX? Or SmallStrXX ? (SmallVector is a pretty common for this kind of thing.) Or FixedStrXX ?

**Comment by ocornut** [comment]
I like the shortness of it in most cases...
Perhaps we should just move it to a namespace + add a define to typedef the types or not in the global namespace.?

Or, a silly workaround would be to just remove Str32 if that's the only conflicting type..

**Comment by jlaumon** [comment]
I agree the name is perfect, so it's hard to accept a longer one...

I think I'd prefer adding a define to remove Str32 than adding a namespace + a define to remove the namespace (because I would be tempted to use it and then I'll find myself in the same situation again ^^).

Another silly workaround would be to add `#define Str32 Str32_Mac` before every mac include and `#undef` it after 😛

**Comment by ocornut** [comment]
Let's replace it with Str30 and call it a day (and maybe keep Str32 commented out with a comment about this)

**Comment by ocornut** [comment]
Maybe add a define to keep Str32, off by default, to ease the workaround for people who codebase may break (but I don't think many people use this at all, hey).

**Comment by jlaumon** [comment]
👍

**Comment by jlaumon** [comment]
I have some free time, I'll make a PR.

**Comment by jlaumon** [comment]
Fixed by #8
